- name: check if homebrew is installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_stats

- name: install homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: homebrew_stats.stat.exists == false

- name: update homebrew
  homebrew:
    update_homebrew: true
  when: package_update

- name: upgrade homebrew packages
  homebrew:
    upgrade_all: true
  when: package_upgrade
