- name: Install yabai with homebrew
  community.general.homebrew:
    name: yabai
    state: present
  register: yabai_installed

- name: Start yabai service
  ansible.builtin.shell: yabai --install-service
  when: yabai_installed.changed
