- name: Install yabai with homebrew
  homebrew:
    name: yabai
    state: present
  register: yabai_installed

- name: Start yabai service
  shell: yabai --install-service
  when: yabai_installed.changed
