- name: Find dotnet {{ channel }}
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/.dotnet/shared/Microsoft.NETCore.App"
    file_type: directory
    patterns: "^{{ channel }}.*"
    recurse: false
    use_regex: true
  register: found_runtimes

- name: Install dotnet with dotnet-install.sh
  ansible.builtin.shell: |
    set -o pipefail
    curl --proto '=https' -sSf https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh | bash -s -- --channel {{ channel }} --runtime dotnet
  when: found_runtimes.matched == 0
  changed_when: found_runtimes.matched == 0
