- name: Install homebrew
  ansible.builtin.shell:
    cmd: $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)
    executable: /bin/bash
    creates: /opt/homebrew/bin/brew

- name: Update homebrew
  community.general.homebrew:
    update_homebrew: true
  when: package_update

- name: Upgrade homebrew packages
  community.general.homebrew:
    upgrade_all: true
  when: package_upgrade
