- name: Darwin | Convert Linux policies to MacOS
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ ansible_env.USER }}"
  ansible.builtin.script: linux_to_mac.sh /tmp/chromium-policies.json
  changed_when: true
