- name: Git clone Alacritty
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty.git"
    dest: "{{ ansible_env.HOME }}/alacritty"
    version: "master"
    depth: 1
  notify:
    - "{{ ansible_os_family }} | Build Alacritty"
    - "{{ ansible_os_family }} | Post Build Binary"
