- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- import_tasks: osx.yml
  when: ansible_os_family == "Darwin"

- name: Check if gruvbox directory exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.vim/pack/default/start/gruvbox"
  register: gruvbox_stats

- name: Install gruvbox theme
  ansible.builtin.git:
    repo: "https://github.com/morhetz/gruvbox.git"
    dest: "~/.vim/pack/default/start/gruvbox"
  when: not gruvbox_stats.stat.exists
