- name: Check if rust is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  register: rust_stats

- name: Install rust with rustup
  ansible.builtin.shell: |
    set -o pipefail
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  when: not rust_stats.stat.exists
