- name: Install rust with rustup
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
