- name: Update pacman
  become: true
  community.general.pacman:
    update_cache: true
  when: package_update

- name: Upgrade pacman packages
  become: true
  community.general.pacman:
    upgrade: true
  when: package_upgrade
