- name: Install git-credential-manager as dotnet tool
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.dotnet/dotnet tool install -g git-credential-manager"
    creates: "{{ ansible_env.HOME }}/.dotnet/tools/git-credential-manager"
