# assume MacOS Ventura
- name: Install autokbisw binary
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      mkdir -p /usr/local/bin \
      && cd /usr/local/bin \
      && curl \
          --proto '=https' \
          https://github.com/ohueter/autokbisw/releases/download/{{ version }}/autokbisw-{{ version }}.ventura.tar.gz \
      | sudo tar -zxvf -
    creates: /usr/local/bin/autokbisw

- name: Install autokbisw service
  ansible.builtin.copy:
    src: eu.byjean.autokbisw.plist
    dest: "{{ ansible_env.HOME }}/Library/LaunchAgents/eu.byjean.autokbisw.plist"
    mode: "0644"

- name: Start service eu.byjean.autokbisw
  community.general.launchd:
    name: eu.byjean.autokbisw
    state: started
    enabled: true
