- name: Archlinux | Install Xorg with pacman
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - xorg-server
    - xorg-xinit
    - xorg-xrandr
    - xclip
