- name: Archlinux | Install OpenJDK with pacman (version {{ version }})
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - java-environment-common
    - java-runtime-common
    - jdk{{ version }}-openjdk

- name: Archlinux | Link environment file using archlinux-java
  become: true
  ansible.builtin.command: archlinux-java set java-{{ version }}-openjdk
  changed_when: true
