- name: Archlinux | Install gnome-keyring with pacman
  become: true
  community.general.pacman:
    name: gnome-keyring
    state: present

- name: Archlinux | Check /etc/pam.d/login
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/login"
    line: "auth       optional     pam_gnome_keyring.so"
    state: present
  check_mode: true
  notify: Archlinux | Gnome/Keyring PAM step

- name: Archlinux | Set login as default keyring
  ansible.builtin.copy:
    src: default
    dest: "{{ ansible_env.HOME }}/.local/share/keyrings/default"
    mode: "0644"
