- name: Load OS-specific vars
  ansible.builtin.include_vars: "vars/{{ ansible_distribution }}.yml"

- name: Load OS-specific tasks
  ansible.builtin.include_tasks: "tasks/{{ ansible_distribution }}.yml"

- name: Check if the firefox profile directory exists
  ansible.builtin.find:
    paths: "{{ firefox_profile_dir }}"
    file_type: directory
    recurse: false
  register: firefox_profile_stats

- name: Git clone firefox-push-pull-service
  ansible.builtin.git:
    repo: "https://github.com/skeletony007/firefox-push-pull-service.git"
    dest: "{{ ansible_env.HOME }}/personal/firefox-push-pull-service"
    depth: 1
  when: not firefox_profile_stats.matched

- name: Create profile using firefox-push-pull-service
  ansible.builtin.shell: cd '{{ ansible_env.HOME }}/personal/firefox-push-pull-service' && ./create
  when: not firefox_profile_stats.matched
