- name: Load OS-specific vars
  ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Load OS-specific tasks
  ansible.builtin.include_tasks: "tasks/{{ ansible_os_family }}.yml"

- name: Copy policy file
  become: true
  ansible.builtin.copy:
    src: firefox/distribution/policies.json
    dest: "{{ paths.policy }}"
    mode: "0644"

- name: Setup profile {{ profile_name }}
  block:
    - name: Find profile {{ profile_name }}
      ansible.builtin.find:
        paths: "{{ paths.profiles }}"
        file_type: directory
        patterns: "*.{{ profile_name }}"
        recurse: false
      register: found_profiles
      failed_when: found_profiles.matched == 0
  rescue:
    - name: Create profile {{ profile_name }}
      ansible.builtin.command:
        argv:
          - "{{ firefox_cmd }}"
          - "-headless"
          - "-CreateProfile"
          - "{{ profile_name }}"
      changed_when: true
    - name: Find profile {{ profile_name }}
      ansible.builtin.find:
        paths: "{{ paths.profiles }}"
        file_type: directory
        patterns: "*.{{ profile_name }}"
        recurse: false
      register: found_profiles
      failed_when: found_profiles.matched == 0

- name: Set found profile {{ profile_name }}
  ansible.builtin.set_fact:
    profile_path: "{{ found_profiles.files[0].path }}"
  failed_when: found_profiles.matched != 1

- name: Copy profile data
  ansible.builtin.copy:
    src: profile/
    dest: "{{ profile_path }}"
    mode: "0644"

- name: Load other tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - "tasks/arkenfox.yml"
    - "tasks/tridactyl.yml"
