# sets firefox_profile_dir
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
- import_tasks: osx.yml
  when: ansible_os_family == "Darwin"

- name: Check if the firefox profile directory exists
  ansible.builtin.find:
    paths: "{{ firefox_profile_dir }}"
    file_type: directory
    recurse: false
  register: firefox_profile_stats

- name: Git clone firefox-push-pull-service
  ansible.builtin.git:
    repo: https://github.com/skeletony007/firefox-push-pull-service.git
    dest: ~/personal/firefox-push-pull-service
  when: not firefox_profile_stats.matched

- name: Create profile using firefox-push-pull-service
  shell: cd ~/personal/firefox-push-pull-service && ./create
  when: not firefox_profile_stats.matched
