- name: passff-host | Check for {{ paths.passff_host }}
  ansible.builtin.stat:
    path: "{{ paths.passff_host }}"
  register: passff_host_stats

- name: passff-host | Install passff-host
  ansible.builtin.shell: |
    set -o pipefail
    curl -sS 'https://codeberg.org/PassFF/passff-host/releases/download/latest/install_host_app.sh' | bash -s -- firefox
  when: not passff_host_stats.stat.exists
