- name: tridactyl | Load OS-specific vars
  ansible.builtin.include_vars: "vars/tridactyl-{{ ansible_os_family }}.yml"

- name: tridactyl | Load main vars
  ansible.builtin.include_vars: "vars/tridactyl.yml"

- name: tridactyl | Install Tridactyl native messenger
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl --proto '=https' -sSf https://raw.githubusercontent.com/tridactyl/native_messenger/master/installers/install.sh | sh -s -- master
    creates: "{{ manifest_file }}"
