- name: arch | Install pass with pacman
  become: true
  community.general.pacman:
    name: pass
    state: present

- name: arch | Install pass-otp with pacman
  become: true
  community.general.pacman:
    name: pass-otp
    state: present
