- name: arch | Install nodejs with pacman
  become: true
  pacman:
    name: nodejs
    state: present

- name: arch | Install npm with pacman
  become: true
  pacman:
    name: npm
    state: present
