- name: Load OS-specific tasks
  ansible.builtin.include_tasks: "tasks/{{ ansible_os_family }}.yml"

- name: Ensure /etc/shells includes {{ lookup('pipe', 'which zsh') }}
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ lookup('pipe', 'which zsh') }}"
    state: present

- name: Change shell to zsh
  become: true
  ansible.builtin.shell: chsh -s "$(which zsh)"
  when: lookup('pipe', 'echo $SHELL') != lookup('pipe', 'which zsh')
