- name: Archlinux | Install PipeWire with pacman
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - pipewire-jack
    - pipewire-alsa
    - pipewire-pulse
