- name: Load OS-specific variables
  ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Download Ubuntu Mono Nerd Fonts (Regular and Bold)
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {
        url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ version }}/patched-fonts/UbuntuMono/Regular/UbuntuMonoNerdFontMono-Regular.ttf",
        dest: "{{ fonts_dir }}/UbuntuMonoNerdFontMono-Regular.ttf",
      }
    - {
        url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ version }}/patched-fonts/UbuntuMono/Bold/UbuntuMonoNerdFontMono-Bold.ttf",
        dest: "{{ fonts_dir }}/UbuntuMonoNerdFontMono-Bold.ttf",
      }
