# sets fonts_dir
- import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- import_tasks: osx.yml
  when: ansible_os_family == 'Darwin'

- name: Check if ubuntu mono nerd font is already installed
  ansible.builtin.stat:
    path: "{{ fonts_dir }}/UbuntuMonoNerdFontMono-Regular.ttf"
  register: nerd_fonts_stats

- name: Install ubuntu mono nerd font
  shell: |
    mkdir -p '{{ fonts_dir }}'
    curl -f https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ version }}/patched-fonts/UbuntuMono/Regular/UbuntuMonoNerdFontMono-Regular.ttf > {{ fonts_dir }}/UbuntuMonoNerdFontMono-Regular.ttf
    curl -f https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ version }}/patched-fonts/UbuntuMono/Bold/UbuntuMonoNerdFontMono-Bold.ttf > {{ fonts_dir }}/UbuntuMonoNerdFontMono-Bold.ttf
  when: not nerd_fonts_stats.stat.exists
