## https://github.com/ansible/ansible-lint
name: ansible-lint
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".ansible-lint"
      - ".editorconfig"
      - ".github/**"
      - ".prettierrc.toml"
      - "README*"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".ansible-lint"
      - ".editorconfig"
      - ".github/**"
      - ".prettierrc.toml"
      - "README*"
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
