- name: Darwin | Git clone dmenu
  ansible.builtin.git:
    repo: git://git.suckless.org/dmenu
    dest: "{{ ansible_env.HOME }}/dmenu"
    depth: 1
    force: true
  notify:
    - Darwin | Edit config.mk
    - Darwin | Build dmenu
